### ISSUE TITLE
Build/Quickstart issues

### ISSUE THREAD

**Issue by jcbaillie** [massalabs/docs#110]
I've tried to follow the instructions in the Build/Quickstart section and I ran into a few issues:

**1. Possible deprecated code**

The smart contract code that you get from `npx @massalabs/sc-project-initializer init massa-hello-world` contains the following code:

```
if (!callerHasWriteAccess()) {
    return [];
}
```
while the quickstart uses:
```
if (!Context.isDeployingContract()) {
    return ;
}
```

Which one is correct? Both work, but it can be confusing for a newcomer.

**2. Smart contract address**

After deploying the smart contract with `npm run deploy`, we get this in the shell:

```
> my-massa-sc@0.0.1 deploy
> npm run build && ts-node src/deploy.ts


> my-massa-sc@0.0.1 build C:\Dev\test-massa-sc\massa-hello-world
> npx massa-as-compile

2 files to compile
contract to compile assembly\contracts\main.ts

contract to compile assembly\contracts\run.ts

Wallet Address: AU1qjC3YSypRFbYgFQ52myXRywR1bMcxc2wzKi9at8RvJFbWkq68 has balance (candid
ate, final) = (399.287, 399.287)
Sending operation with 100000000 MAS coins...
Operation successfully submitted with id: O15orXWAQH1Gk6cLRafyk3dHJHMtZBVSXRKpC7Nh6dzHYa
K3XzN
Waiting for events...
Event Data Received: [
  {
    context: {
      slot: [Object],
      block: 'B18tsWEjyQFik79hHRxhSzu963osAyVgtXHzYyvxsfRpHksLn76',
      read_only: false,
      index_in_slot: 0,
      call_stack: [Array],
      origin_operation_id: 'O15orXWAQH1Gk6cLRafyk3dHJHMtZBVSXRKpC7Nh6dzHYaK3XzN',
      is_final: false,
      is_error: false
    },
    data: 'Greeting has been set'
  },
  {
    context: {
      slot: [Object],
      block: 'B18tsWEjyQFik79hHRxhSzu963osAyVgtXHzYyvxsfRpHksLn76',
      read_only: false,
      index_in_slot: 1,
      call_stack: [Array],
      origin_operation_id: 'O15orXWAQH1Gk6cLRafyk3dHJHMtZBVSXRKpC7Nh6dzHYaK3XzN',
      is_final: false,
      is_error: false
    },
    data: 'Contract deployed at address: AS126AMGtbsyJH4qcxd6sE4s7msyfCmdmHVbqW4jM8VmfGW
35dKVv'
  }
]
Awaiting FINAL transaction status....
Transaction with Operation ID O15orXWAQH1Gk6cLRafyk3dHJHMtZBVSXRKpC7Nh6dzHYaK3XzN has re
ached finality!
```

The smart contract address is never provided. This is in contrast to what is shown in https://docs.massa.net/en/latest/web3-dev/smart-contracts/getting-started.html, where the deploy command ends with: `Contract deployed at address: A12V8...`.

If this is deprecated, we should add a way for the user to get the address from the operation id. It is not obvious.

**Comment by Ben-Rey** [comment]
1. This has been fixed
2. The contract address is in the events: `  data: 'Contract deployed at address: AS126AMGtbsyJH4qcxd6sE4s7msyfCmdmHVbqW4jM8VmfGW`
