### ISSUE TITLE
massa-web3 client initialization

### ISSUE THREAD

**Issue by qdrn** [massalabs/docs#289]
Unless I'm mistaken I think it's weird to put `Sandbox` for the `chainid` in https://docs.massa.net/docs/build/massa-web3#without-wallet-provider.
I think in most cases it will be misleading.

**Comment by Leo-Besancon** [comment]
I think we should definetely avoid the Sandbox chainId for `Custom Client` tab.
For the LocalNet tab, it does replicate the naming of this page https://docs.massa.net/docs/build/networks-faucets/local-network so I think we can keep sandbox there, but it should be clarified and the same everywhere.
