### ISSUE TITLE
Learn - Autonomous SC

### ISSUE THREAD

**Issue by gregLibert** [massalabs/docs#32]
As described here: https://github.com/massalabs/docu-dev/pull/29/files#diff-3fe3b59d1988fd4cfbc13f04b79a9c3912f38fc45117af60d1c8ea9143b4cabb

This includes:

create the subdirectory if needed
update the sidebar and the docusaurus config

**Comment by windushka** [comment]
To be followed by updating the corresponding link here:
https://github.com/massalabs/docu-dev/blob/31-learn-architecture/docs/learn/architecture/basic-concepts.mdx?plain=1#L97
