### ISSUE TITLE
create quickstart

### ISSUE THREAD

**Issue by gregLibert** [massalabs/docs#9]
Create a quick start section that will propose a Hello world DApp:
- with a smart contract
  - exporting a greetings function that can be called with or without a name 
  - recognizing its creator (show case the constructor function)
  - including unit tests
- with a front
  -  using wallet-provider
  - massa-web3
- using Thyra as wallet provider

The idea is to have a step by step guide as well as an already working git repo.

You get get inspiration from https://docs.near.org/develop/quickstart-guide

**Comment by Ben-Rey** [comment]
This has been done https://docs.massa.net/docs/build/hello-world-dapp
